#! /bin/sh 
PATH=/usr/bin
desktopuser=$(/bin/ps -ef  | /bin/grep -oP '^\w+ (?=.*vdagent( |$))') || exit 0
export DISPLAY=:0
XAUTHORITY=$(eval echo "~$desktopuser")/.Xauthority
export XAUTHORITY="$XAUTHORITY"
xrandr --output "$(xrandr | awk '/ connected/{print $1; exit; }')" --auto