- name: Install all the tools
  hosts: localhost
  tasks:
    - name: Include Package Variable
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - "apt.yaml"
        - "cargo.yaml"
        - "git.yaml"
        - "golang.yaml"
        - "python.yaml"
        - "vars.yaml"
    - name: Create README from Template
      ansible.builtin.template:
        src: templates/readme.j2
        dest: README.md
        mode: '644'
        force: true
