# Custom Tasks
- name: Create Master Dirbust Wordlist
  ansible.builtin.script: "custom/dirbust.sh {{ tools_dir }}/Dirbust.txt"
  args:
    creates: "{{ tools_dir }}/Dirbust.txt"

- name: Setup Automatic Resizing
  become: true
  notify: Restart Notify
  block:
    - name: Copy Resize Rules
      ansible.builtin.copy:
        src: "custom/50-x-resize.rules"
        dest: "/etc/udev/rules.d/"
        mode: '0644'

    - name: Copy Resize Script
      ansible.builtin.copy:
        src: "custom/x-resize"
        dest: "/usr/local/bin/"
        mode: '0755'

- name: Install VSCode
  become: true
  block:
    - name: Download VSCode
      ansible.builtin.get_url:
        url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
        dest: "/tmp/vscode.deb"
        mode: "700"

    - name: Install VSCode
      ansible.builtin.apt:
        deb: /tmp/vscode.deb

- name: Disable Sleep and Hibernation
  ansible.builtin.systemd_service:
    service: "{{ item }}"
    masked: true
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
