# Custom Tasks
- name: Create Master Dirbust Wordlist
  ansible.builtin.script: "custom/dirbust.sh {{ tools_dir }}/Dirbust.txt"
  args:
    creates: "{{ tools_dir }}/Dirbust.txt"

- name: Setup Automatic Resizing
  become: true
  notify: Restart Notify
  block:
    - name: Copy Resize Rules
      ansible.builtin.copy:
        src: "custom/50-x-resize.rules"
        dest: "/etc/udev/rules.d/"
        mode: '0644'

    - name: Copy Resize Script
      ansible.builtin.copy:
        src: "custom/x-resize"
        dest: "/usr/local/bin/"
        mode: '0755'

